version: "3.7"
services:
  postgres-dev:
    # image: postgres:12.3
    # volumes:
    #   - type: bind
    #     source: ./postgres
    #     target: /docker-entrypoint-initdb.d
    build: ./images/postgresql
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toshogakari
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  backend:
    build: ./images/ruby
    volumes:
      - type: bind
        source: ./www
        target: /var/www
      - bundle_install:/usr/local/bundle
      - cache:/cache
    working_dir: /var/www/
    ports:
      - "3000:3000"
    command: ash -c "bundle install && rails s -b 0.0.0.0"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - SPROCKETS_CACHE=/cache
  webpacker:
    build: ./images/ruby
    volumes:
      - type: bind
        source: ./www
        target: /var/www
      - bundle_install:/usr/local/bundle
    working_dir: /var/www/
    ports:
      - '3035:3035'
    command: ./bin/webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    depends_on:
      - backend
  redis:
    image: redis
volumes: 
  bundle_install:
  cache: