version: 3.7
services:
  postgres-dev:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
  rails:
    image: ruby:2.7.0-alpine3.11
  redis:
    image: redis