version: "3.7"
services:
  postgres-dev:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
  rails:
    build: ./images/ruby
    volumes:
      - type: bind
        source: ./www
        target: /var/www
    working_dir: /var/www
  redis:
    image: redis