version: "3.7"
services:
  postgres-dev:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
  web:
    build: ./images/ruby
    volumes:
      - type: bind
        source: ./www
        target: /var/www
    working_dir: /var/www/first_app
    ports:
      - "3000:3000"
    command: ash -c "bundle install && rails s -b 0.0.0.0"
  redis:
    image: redis